name: $(date:yyyyMMdd)$(rev:.rr)-$(BuildID)

resources:
  repositories:
  - repository: self
    clean: true
  - repository: SdkBuildScripts
    clean: true
    name: SdkBuildScripts
    type: git

trigger:
  branches:
    include:
    - main
    - prerelease

schedules:
- cron: 0 4 * * * # Daily at 4am GMT
  displayName: "Daily main"
  branches:
    include:
    - main
  always: true

extends:
  template: builds/azure-sphere-tools/templates/azure-sphere-tools.yml@SdkBuildScripts