name: $(date:yyyyMMdd)$(rev:.rr)-$(BuildID)

resources:
  repositories:
  - repository: self
    clean: true
  - repository: SdkBuildScripts
    clean: true
    name: SdkBuildScripts
    type: git
    ref: refs/heads/chwhitwo/fix-cg

trigger:
  branches:
    include:
    - main
    - prerelease

extends:
  template: builds/azure-sphere-tools/templates/azure-sphere-tools.yml@SdkBuildScripts