name: $(date:yyyyMMdd)$(rev:.rr)-$(BuildID)

resources:
  repositories:
  - repository: self
    clean: true
  - repository: SdkBuildScripts
    clean: true
    ref: refs/heads/devinejames/dotnet-codeql-round3
    name: SdkBuildScripts
    type: git

trigger:
  branches:
    include:
    - main
    - prerelease

extends:
  template: builds/azure-sphere-tools/templates/azure-sphere-tools.yml@SdkBuildScripts