name: $(date:yyyyMMdd)$(rev:.rr)-$(BuildID)

resources:
  repositories:
  - repository: self
    clean: true
  - repository: SdkBuildScripts
    clean: true
    name: SdkBuildScripts
    type: git
    ref: refs/heads/dev/snehara/replace-scripts
  - repository: oneBranchPipelines
    type: git
    name: OneBranch.Pipelines/GovernedTemplates
    ref: refs/heads/main

trigger:
  branches:
    include:
    - main
    - prerelease

schedules:
- cron: 0 4 * * * # Daily at 4am GMT
  displayName: "Daily main"
  branches:
    include:
    - main
  always: true

variables:
  Codeql.Enabled: true
  PythonVersion: '3.x'
  DotNetVersion: '6.0.x'
  # Disable automatic Nuget Security Analysis injection so we can place the
  # nuget.config files in place and then manually run `task: nuget-security-analysis@0`
  skipNugetSecurityAnalysis: true
  system.debug: true
  ReleaseOrMain: $[
    or(
    eq( variables['Build.SourceBranch'], 'refs/heads/main'),
    startswith(variables['Build.SourceBranch'], 'refs/heads/release')
    ) ]
  WindowsContainerImage: onebranch.azurecr.io/windows/ltsc2019/vse2022:latest

extends:
  template: /v2/OneBranch.NonOfficial.CrossPlat.yml@oneBranchPipelines
  parameters:
    featureFlags:
      WindowsHostVersion:
          Network: KS1
    stages:
    - stage: hello_world_1
      displayName: Hello World 1
      jobs:
      - job: print_hello
        variables:
        - name: ob_outputDirectory
          value: "$(build.ArtifactStagingDirectory)/hello_world"
        displayName: "Print Hello World"

        steps:
        - task: PowerShell@2
          displayName: "Hello World"
          inputs:
            targetType: inline
            script: |
              Write-Output "Hello World"

    - template: builds/azure-sphere-tools/templates/azure-sphere-tools.yml@SdkBuildScripts