name: build

on:
  push:
    branches: [ main, prerelease ]
  pull_request:
    branches: [ main, prerelease ]

env:
  DOTNET_VERSION: '6.0.401' # The .NET SDK version to use
  PYTHON_VERSION: '3.10'

jobs:
  build-csharp:

    name: build-csharp-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3.7.0

    - name: Setup .NET Core
      uses: actions/setup-dotnet@55ec9447dda3d1cf6bd587150f3262f30ee10815 # v3.4.2
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Setup NuGet
      uses: nuget/setup-nuget@296fd3ccf8528660c91106efefe2364482f86d6f # v1.2.0
      with:
        nuget-version: latest

    - name: Run C# build
      shell: pwsh
      run: |
        ./scripts/build-csharp.ps1

  build-python:
    name: build-python-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    
    steps:
    - uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3.7.0

    - name: Setup Python
      uses: actions/setup-python@7f4fc3e22c37d6ff65e88745f38bd3157c663f7c # v4.9.1
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Run Python build
      shell: pwsh
      run: |
        ./scripts/build-python.ps1