name: build

on:
  push:
    branches: [ main, prerelease ]
  pull_request:
    branches: [ main, prerelease ]

env:
  DOTNET_VERSION: '6.0.401' # The .NET SDK version to use
  PYTHON_VERSION: '3.10'

jobs:
  build-csharp:

    name: build-csharp-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Setup .NET Core
      uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6.0.0
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Setup NuGet
      uses: nuget/setup-nuget@b26b823c478ee115be5c9403e62c90b0bf943843 # v3.1.0
      with:
        nuget-version: latest

    - name: Run C# build
      shell: pwsh
      run: |
        ./scripts/build-csharp.ps1

  build-python:
    name: build-python-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Setup Python
      uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Run Python build
      shell: pwsh
      run: |
        ./scripts/build-python.ps1